project:
  type: website

website:
  site-url: https://paciorek.github.io/course-site-quarto-test/
  sidebar:
    style: docked
    title: "Stat 999"
    logo: assets/stat_bear.png
    tools:
      - icon: github
        href: https://github.com/paciorek/course-site-quarto-test
    contents:
      - href: index.qmd
        text: Home / Schedule
      - href: syllabus.qmd
        text: Syllabus
      - href: staff.qmd
        text: Staff
      - href: calendar.qmd
        text: Calendar
      - section: "Units"
        contents:
          - units/unit1.qmd
          - units/unit2.ipynb
          - units/unit3.qmd
      - href: data.qmd
        text: Datasets
      - href: license.qmd
        text: License
          

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true



